# work computer 配置

spring:
  application:
    name: ubsp-be-work
    
  # 数据库配置 (工作电脑的虚拟机地址)
  datasource:
    url: jdbc:mysql://10.0.120.208:3306/ubsp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: rootTsk@123
    
  # Redis配置  
  data:
    redis:
      host: 10.0.120.208
      port: 6379
      database: 0
      password: # 如果有密码则填写

# SeaTunnel 配置
seatunnel:
  api:
    base-url: http://10.0.120.208:8082
    # 认证方式: none, basic, bearer, token, custom
    auth-type: basic
    # Basic认证配置
    username: admin
    password: admin
    # Token认证配置（当auth-type为bearer/token/custom时使用）
    # token: your-token
    # auth-header: Authorization  # 自定义认证头名称（仅当auth-type为custom时使用）
    output-root: /tmp/seatunnel

# 日志配置
logging:
  level:
    com.udan.ubsp: debug
    root: info