# 生产环境配置

spring:
  application:
    name: ubsp-be-prod
    
  # 数据库配置 (生产环境)
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/ubsp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ${DB_USER}
    password: ${DB_PASSWORD} # 生产环境建议使用环境变量
    
  # Redis配置  
  data:
    redis:
      host: prod-redis-server
      port: 6379
      database: 0
      password: # 如果有密码则填写 ${REDIS_PASSWORD}  生产环境建议使用环境变量

# SeaTunnel 配置
seatunnel:
  api:
    # http://seatunnel-server:8082
    base-url: ${SEATUNNEL_API_BASE_URL:}
    # 认证方式: none, basic, bearer, token, custom
    auth-type: basic
    # Basic认证配置
    username: ${SEATUNNEL_USERNAME:}
    password: ${SEATUNNEL_PASSWORD:}
    # Token认证配置
    # token:
    # 自定义认证头名称（仅当auth-type为custom时使用）
    # auth-header: Authorization
    output-root: /home/uduser/ubsp/ubsp-be/data

# 日志配置
logging:
  level:
    com.udan.ubsp: info
    root: warn
  # 使用Logback配置文件进行更精细的日志管理
  config: classpath:logback-spring.xml